name: Send Slack Notification

on:
  workflow_run:
    workflows: ["Main"]  # Replace "YourWorkflowName" with the name of your main workflow

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Job status"
                  }
                }
              ]
            }
        #env:
         # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
