jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Send custom JSON data to Slack workflow
        run: echo "hello from reusable yaml"
