name: Main

#on: push
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Want to upload apk to github?
        options: 
        - Yes
        - No
      message:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Generate release tag
        if: github.event.inputs.name == 'Yes'
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Move source code (if needed)
        if: github.event.inputs.name == 'Yes'
        run: |
          mv /path/to/source/code/* /temp_directory/
      - name: Release user firmware
        if: github.event.inputs.name == 'Yes'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            Release.txt
