name: Main

#on: push
on:
    workflow_dispatch:
        inputs:
            upload_to_github:
              description: 'Do you want to release/upload to Github'
              required: true
              default: 'No'
jobs:
  my_custom_job:
    runs-on: ubuntu-latest

    # Include the reusable workflow from reusable.yml
    steps:
      - name: Include Reusable Workflow
        #uses: action.yml@main
