name: Main

#on: push
on:
    workflow_dispatch:
        inputs:
            upload_to_github:
              description: 'Do you want to release/upload to Github'
              required: true
              default: 'No'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Generate release tag
        if: github.event.inputs.upload_to_github == 'Yes'
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release user firmware
        if: github.event.inputs.upload_to_github == 'Yes'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            Release.txt
