name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt && echo ${{ github.sha }} > Release2.txt
      - name: Test
        run: cat Release.txt
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release2.txt # the folder which has all the files that you want to release
          tag: ${{ steps.tag.outputs.release_tag }}
          overwrite: true
          file_glob: true
