name: My Custom Workflow

on:
    workflow_dispatch:


jobs:
  my_custom_job:
    runs-on: ubuntu-latest

    # Include the reusable workflow from reusable.yml
    steps:
      - name: Include Reusable Workflow
        uses: drsr111/FirstRepo/composite@master
